/*
 Quantcast measurement tag
 Copyright (c) 2008-2018, Quantcast Corp.
*/
window.__qc=function(b){if(b.__qc)return b.__qc;var B="a ce cm dst enc fpa fpan je ns ogl rf tzo sr".split(" "),m=b.document,z=b.navigator,D="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),F=!1,M=!1,G=0,g=[],N=[],p=[],f=[],u={},h=0,e=[],l=null,r={},v={},ia=null,n,Y=[].slice,ja,Z,O,q,A,$,P,ka,la,ma,H,aa,Q,R,na,oa,I,pa,qa,ra,sa,s,ta,C,ua,S,va,wa,ba,xa,ya,ca,w,za,J,Aa,T,
Ba,Ca,U,Da,da,ea,Ea,fa,E,V,K,L,ga,ha,W,t=function(a){try{return{init:R,hash:Q,push:na,rules:Ba,hasRules:U,defaults:Ea,__qc:function(){return!0}}[a].apply(null,Y.call(arguments,1))}catch(c){return!1}};t.evts=0;t.v=2;t.SD=D;t.qpixelsent=[];T=function(a){var c=a?a.length||0:0,d;for(d=0;d<c;d++)if(!a[d])return!1;return!0};ea=function(a){(a=a||b._qacct)&&(ca(f,a)||f.push(a))};ca=function(a,c){var d=a.length,b;for(b=0;b<d;b++)if(a[b]===c)return!0;return!1};J=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};
Aa=function(a){var c,d;c=J(a);if("array"===c)return a.slice(0);if("object"===c){c={};for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c}return"string"===c?""+a:a};na=function(a,c){s(a,c)};U=function(a){return ca(p,a)};Ea=function(a,c){var d;a&&((d=r[a])&&(c=L(c,d)),c.qacct&&delete c.qacct,r[a]=c)};fa=function(a){var c,d;if(q(a))for(c in a)if("string"==typeof a[c]){c=a.event||"load";d=a.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==d&&"ad"!==d?s(a):(d=a.qacct||b._qacct,a.qacct=d,c=(c=v[d])?
L(c,a):a,v[d]=c);ea(a.qacct);break}else"object"==typeof a[c]&&null!=a[c]&&fa(a[c])};L=function(a,c){var d={};d.qacct=a.qacct||c.qacct;d.event="load"===a.event||"load"===c.event?"load":a.event&&c.event?a.event||c.event:null;d.media=null;d.media="webpage"===a.media||"webpage"===c.media?"webpage":"ad"===a.media||"ad"===c.media?"ad":a.media||c.media;ba(d,a,c);ba(d,c,a);d.event||delete d.event;d.media||delete d.media;return d};ba=function(a,c,d){var b,X,h,e,l,g;for(b in c)c.hasOwnProperty(b)&&!a.hasOwnProperty(b)&&
(X=c[b],h=d[b],e="",l=!!X&&"string"==typeof X,g=!!h&&"string"==typeof h,l&&(e=X),l&&g&&(e+=","),g&&(e+=h),a[b]=e)};E=function(){var a=[],c,d;if(!(0<h)){za();for(c in v)v.hasOwnProperty(c)&&v[c]&&(d=v[c],a.push(d),delete v[c]);1==a.length&&s(a[0]);1<a.length&&s(a)}};V=function(){var a=[],c,d,b;b=f.slice(0);for(c=0;c<b.length;c++)d=b[c],U(d)||a.push(d);if(0===a.length)E();else for(c=0;c<a.length;c++)d=a[c],p.push(d),xa(d)};ya=function(){for(var a;e[0]&&("loaded"==e[0].readyState||"complete"==e[0].readyState);)a=
e.shift(),a.onreadystatechange=null,l.parentNode.insertBefore(a,l),K()};xa=function(a){var c,d;c=("https:"===m.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+a+".js";l=l||m.scripts[0];h++;d=m.createElement("script");"async"in d?(d.src=c,d.async=!1,d.onload=function(){u[a]=0;K()},d.onerror=function(){u[a]=1;K()},l.parentNode.insertBefore(d,l)):d.readyState?(u[a]=2,e.push(d),d.onreadystatechange=ya,d.src=c):(u[a]=4,K())};K=function(){h-=0<h?1:0;E()};Ba=function(){var a=!0,c,d,
b;if(arguments.length){b=function(c){a?fa(c):s(c,!0)};for(c=0;c<arguments.length;c++)d=Y.call(arguments[c],0),d.splice(1,0,b),Ca.apply(null,d);a=!1;F&&E()}};Ca=function(a,c){var d=[],b=[],e=c||s,h,l,g,f,r;if((h=Y.call(arguments,2))&&h.length){l=h[0]||T;g=h[1];f=h[2];h=f.length;for(r=0;r<h;r++)d.push(!1),b.push(null);d={p:a,f:d,r:l,c:f,a:g,v:b};U(a)||p.push(a);N.push(d);Da(d,e)}else p.push(a),u[a]=6};Da=function(a,c){var d=a?a.c?a.c.length:0:0,b;for(b=0;b<d;b++)(function(d){var b,h;try{b=a.c[d][0],
h=a.c[d].slice(1),h.splice(0,0,function(b){a.f[d]=!0;a.v[d]=b;da(a,c)}),b.apply(null,h)}catch(e){a.f[d]=!0,a.v[d]=!1,da(a,c)}})(b)};da=function(a,c){var d=a.a,b=a.v,h=a.r||T,e,l,g,f,r,k;(e=T(a.f))&&(e=e&&h(b));if(e)for(b=0;b<d.length;b++)try{l=d[b][0];g=1<d[b].length?d[b].slice(1):[];g=g.concat(a.v);f=l.apply(null,g);r={qacct:a.p,event:"rule"};for(k in f)f.hasOwnProperty(k)&&"qacct"!==k&&(r[k]=f[k]);c(r)}catch(q){}};ja=function(){return Z(0)!==Z(6)?1:0};Z=function(a){a=new Date(2E3,a,1,0,0,0,0);var c=
a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1));return a-c};O=function(a){return a.replace(/\./g,"%2E").replace(/,/g,"%2C")};A="function"===typeof encodeURIComponent?encodeURIComponent:O;q=function(a){return"undefined"!=typeof a&&null!=a};$=function(){return Math.round(2147483647*Math.random())};P=function(a){var c="",d=m.cookie,b;if(!d)return c;b=d.indexOf(a+"\x3d");a=b+a.length+1;-1<b&&(c=d.indexOf(";",a),0>c&&(c=d.length),c=d.substring(a,c));return c};ka=function(){var a="",c=H(),
d,b,h;if(1===G)return";fpan\x3du;fpa\x3d";d=Q(c);for(b=0;b<D.length;b++)if(D[b]===d)return";fpan\x3du;fpa\x3d";d=new Date;b=P("__qca");if(0<b.length){try{h=+b.split("-")[2],338688E5<d-h&&(m.cookie=["__qca\x3d",b,"; expires\x3d",(new Date(h+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""))}catch(e){}a+=";fpan\x3d0;fpa\x3d"+b}0===P("__qca").length&&(b="P0-"+$()+"-"+d.getTime(),m.cookie=["__qca\x3d",b,"; expires\x3d",(new Date(d.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",
c].join(""),b=P("__qca"),a=0<b.length?a+(";fpan\x3d1;fpa\x3d"+b):a+";fpan\x3du;fpa\x3d");return a};la=function(a){m.cookie=a+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+H()};H=function(){var a,c,b,h;a=m.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));c=a.split(".");h=c.length;if(3>h)return a;b=c[h-1];return 3>b.length?a:a=c[h-2]+"."+b};aa=function(a,c){var b;for(b=0;b<c.length;b++)a^=c.charCodeAt(b),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};Q=function(a){var c;
c=aa(2166136261,a);a=aa(3386659096,a);return Math.round(Math.abs(c*a)/65536).toString(16)};va=function(a){var c,b;if(a&&"object"===J(a))for(b=0;b<B.length;b++)c=B[b],a.hasOwnProperty(c)&&a[c]&&delete a[c]};S=function(a,c,d){var h={},e=b._qacct,l=null,g="webpage",f="load",m={},n,k,e=c?c.qacct||b._qacct:b._qacct;n=v[e];c?n&&(c=L(c,n)):c=n;e&&delete v[e];va(c);if(null!=c)for(k in c)m[k]=void 0!==c[k],c.hasOwnProperty(k)&&"string"===typeof k&&"string"===typeof c[k]&&("uid"===k||"uh"===k?(oa()||(l=Q(c[k])),
delete c[k]):"qacct"!==k&&(0<c[k].length?h[k+a]=A(c[k]):m[k]=!1,"media"===k&&(g=c[k]),"event"===k&&(f=c[k])));if("string"!==typeof e){if(!q(b._qacct)||0===b._qacct.length)return null;e=b._qacct}if(e){if(n=r[e])for(k in n)"string"===typeof k&&n.hasOwnProperty(k)&&!m[k]&&(h[k+a]=A(n[k]),"media"===k&&(g=n[k]),"event"===k&&(f=n[k]))}else return null;m=u[e];q(m)||(m=3);h["rf"+a]=""+m;"string"===typeof l&&(c.uh=l,h["uh"+a]=A(l));if("webpage"===g&&"load"===f){for(c=0;c<t.qpixelsent.length;c++)if(t.qpixelsent[c]===
e&&!d)return null;t.qpixelsent.push(e)}"ad"===g&&(G=1);h["a"+a]=e;return h};ua=function(a){var c=[],b;for(b in a)a[b]&&a.hasOwnProperty(b)&&c.push(b+"\x3d"+a[b]);return c.join(";")};wa=function(){var a=m.getElementsByTagName("meta"),c="",b,h,e,l;for(b=0;b<a.length;b++){e=a[b];if(1E3<=c.length)return c;q(e)&&q(e.attributes)&&q(e.attributes.property)&&q(e.attributes.property.value)&&q(e.content)&&(h=e.attributes.property.value,e=e.content,3<h.length&&"og:"===h.substring(0,3)&&(0<c.length&&(c+=","),
l=80<e.length?80:e.length,c+=O(h.substring(3,h.length))+"."+O(e.substring(0,l))))}return A(c)};ma=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};oa=function(){var a=!1;q(b.external)&&(a=b.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());return a||"1"==z.doNotTrack||"yes"===z.doNotTrack||"1"==z.msDoNotTrack};s=function(a,c){var d="function"===typeof encodeURIComponent?"n":"s",h=$(),
e="",l="",f="",r="",n="",v="u",k="1",s=[],x,y,p,u,w;G=0;q(t.qpixelsent)||(t.qpixelsent=[]);if(q(a))if(x=J(a),"object"===x)y=S("",a,c);else{if("array"===x)for(x=0;x<a.length;x++)p=S("."+(x+1),a[x],c),y=0===x?p:L(y,p)}else"string"===typeof _qacct&&(y=S("",null,c));y&&(x=z.cookieEnabled?"1":"0","undefined"!=typeof z.javaEnabled&&(v=z.javaEnabled()?"1":"0"),q(b._qmeta)&&(l=";m\x3d"+A(b._qmeta),b._qmeta=null),self.screen&&(e=screen.width+"x"+screen.height+"x"+screen.colorDepth),p=new Date,u=ja(),w=ka(),
b.location&&b.location.href&&(f=A(b.location.href)),m&&m.referrer&&(n=A(m.referrer)),b.self===b.top&&(k="0"),y.url?r=f:y.url=f,y.ref||(y.ref=n||""),f=wa(),n=ua(y),s.push("/pixel;r\x3d"+h+";"+n+w+";ns\x3d"+k+";ce\x3d"+x),s.push((y.ref?"":";ref\x3d")+";je\x3d"+v+";sr\x3d"+e+";enc\x3d"+d+";dst\x3d"+u+";et\x3d"+p.getTime()+";tzo\x3d"+p.getTimezoneOffset()+(r?";ourl\x3d"+r:"")+l+";ogl\x3d"+f),g.push(s),C())};ta=function(a){var c=new Image;a=[b.location.protocol,"//pixel.",pa(n)?"quantserve.com":"quantcount.com",
a[0],";cm\x3d",ma(n),a[1]].join("");c.alt="";c.src=a;c.onload=function(){c&&"number"==typeof c.width&&3===c.width&&la("__qca")}};C=function(){if(n)for(;g.length;)ta(g.shift());else sa()};pa=function(a){return!0===a||1===a||1===a||q(a)&&"approved"===a.consent?!0:!1};sa=function(){if(!q(n)){if(b.top===b.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){qa("getConsent","advertising");return}}else if(b.postMessage&&"object"===typeof JSON){ra("getConsent","advertising");
return}n=1}C()};qa=function(a,c){n=PrivacyManagerAPI.callApi(a,"quantserve.com",H(),"truste.com",c);C()};ra=function(a,c){var d={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",domain:H(),authority:"truste.com",type:c}};if(b.addEventListener)b.addEventListener("message",I,!1);else if(b.attachEvent)b.attachEvent("onmessage",I);else{n=!0;C();return}try{b.top.postMessage(JSON.stringify(d),"*")}catch(e){}ia=setTimeout(function(){q(n)||(n=!0,C())},25)};I=function(a){var c=
null;if(a.source===window.top){try{c="object"===typeof JSON&&JSON.parse(a.data)}catch(d){}c&&"object"===typeof c.PrivacyManagerAPI&&(clearTimeout(ia),b.removeEventListener?window.removeEventListener("message",I,!1):b.detachEvent&&window.detachEvent("onmessage",I),n=c.PrivacyManagerAPI,C())}};ga=function(){var a=arguments,c,b;w([].slice.call(a));for(b=0;b<a.length;b++)c=a[b],s(c);f.length?V():E()};w=function(a){var c=J(a);if("array"===c)for(c=0;c<a.length;c++)w(a[c]);else"object"===c&&ea(a.qacct||
b._qacct)};za=function(){var a;M||b._qevents.length||b.ezt.length||"undefined"===typeof _qacct||(s({qacct:b._qacct}),M=!0);if(!t.evts){for(a in b._qevents)b._qevents.hasOwnProperty(a)&&s(b._qevents[a]);for(a in b.ezt)b.ezt.hasOwnProperty(a)&&s(b.ezt[a]);b._qevents={push:ga};b.ezt.push=function(){var a=arguments,d;if(q(b.queueManager))for(d=0;d<a.length;d++)b.queueManager.push(a[d]);else ga.apply(this,arguments)};t.evts=1}};W=function(a){var c;a&&(c=Aa(a),w(a),b._qevents.push(c))};ha=function(a){a.push=
function(){w([].slice.call(arguments));V();return[].push.apply(a,arguments)}};R=function(){q(b._qevents)||(b._qevents=[]);q(b.ezt)||(b.ezt=[]);W(b._qoptions);W(b.qcdata);W(b.smarttagdata);t.evts||(ha(b._qevents),ha(b.ezt));w(b.ezt);w(b._qevents);w({qacct:b._qacct});b._qoptions=null;f.length?V():E();F=!0};b.quantserve=b.quantserve||R;t.quantserve=R;return t}(window);
try{__qc("hasRules","p-fw53_-Tq3MNK1")||function(b,B,m){var z=function(b){var e=m.createElement("a");e.href=b;return e},D=function(b){return b.replace(/^[\s\ufeff\xA0]+|[\s\ufeff\xA0]+$/g,"")},F=function(b){return{}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()},M=function(b,e){if(!e)return e;var l,f;l="keywords"===b.toLowerCase()||0===b.toLowerCase().indexOf("qc:")?!0:!1;f=0===b.toLowerCase().indexOf("qc:")?!1:!0;f&&(e=e.replace(/\.+/g," "));if(l){f=e.split(",");for(l=0;l<f.length;l++)f[l]=
D(f[l]);return f}return D(e.replace(/,+/g," "))},G=function(b,e,f){return b?"nc"===b?!e||!f||0>e.indexOf(f):"eq"===b?e===f:"sw"===b?0===e.indexOf(f):"ew"===b?(b=e.length-f.length,e=e.lastIndexOf(f,b),-1!==e&&e===b):"c"===b?0<=e.indexOf(f):!1:!1},g=function(b,e,f){var g;g=B.top===B.self?m.location.href:z(m.referrer).href;G(e,g,f)?b(g):b(!1)},N=function(b,e,f){e=document.getElementsByTagName("meta");for(var g,m,p=[],n=0;n<e.length;n++)g=e[n],m=g.getAttribute("name")||g.getAttribute("property"),m==f&&
(p=p.concat(M(f,g.getAttribute("content"))));0<p.length?b(p):b(!1)},p=function(b){return{labels:b}},f=function(b){return"array"===F(b)?p(b.join(",")):p(""+b)},u=function(b,e){var f=[],g;if("array"===F(e)){for(g=0;g<e.length;g++)f.push(b+"."+e[g]);return p(f.join(","))}return p(b+"."+e)},g=["rules",[b,null,[[f,"_campaign.branded.Vertical.Finance.Podcast.Umpqua Bank.Open Account.Episode 301"]],[[g,"c","slate.com/podcasts/open-account/the-nuances-of-poverty--dr--donna-beegle.html"]]],[b,null,[[f,"_campaign.branded.Podcast.Umpqua Bank.Open Account.Episode 301"]],
[[g,"c","slate.com/podcasts/open-account/the-nuances-of-poverty--dr--donna-beegle.html"]]],[b,null,[[u,"Author"]],[[N,"exactmatch","author"]]],[b,null,[[u,"Title"]],[[N,"exactmatch","og:title"]]],[b,null,[[f,"Technology.Future Tense"]],[[g,"c","future_tense"]]],[b,null,[[f,"Slate Plus"]],[[g,"c","slate.com/plus"]]],[b,null,[[f,"Arts.Brow Beat"]],[[g,"c","slate.com/blogs/browbeat"]]],[b,null,[[f,"Arts.Culturebox"]],[[g,"c","culturebox"]]],[b,null,[[f,"News \x26 Politics.Cover Story"]],[[g,"c","cover_story"]]],
[b,null,[[f,"Business.Moneybox"]],[[g,"c","slate.com/blogs/moneybox"]]],[b,null,[[f,"News \x26 Politics.The Slatest"]],[[g,"c","the_slatest"]]],[b,null,[[f,"Life.Normal"]],[[g,"c","slate.com/blogs/normal"]]],[b,null,[[f,"Life.Outward"]],[[g,"c","slate.com/blogs/outward"]]],[b,null,[[f,"Life.Lexicon Valley"]],[[g,"c","slate.com/blogs/lexicon_valley"]]],[b,null,[[f,"Sports"]],[[g,"c","slate.com/articles/sports"]]],[b,null,[[f,"Video"]],[[g,"c","slate.com/articles/video"]]],[b,null,[[f,"Podcasts"]],
[[g,"c","slate.com/articles/podcasts"]]],[b,null,[[f,"Health \x26 Science"]],[[g,"c","slate.com/articles/health_and_science"]]],[b,null,[[f,"Blogs.Atlas Obscura"]],[[g,"c","slate.com/blogs/atlas_obscura"]]],[b,null,[[f,"Double X.The XX Factor"]],[[g,"c","slate.com/blogs/xx_factor"]]],[b,null,[[f,"Blogs.Bad Astronomy"]],[[g,"c","slate.com/blogs/bad_astronomy"]]],[b,null,[[f,"Photos"]],[[g,"c","slate.com/blogs/behold"]]],[b,null,[[f,"Life.Dear Prudence"]],[[g,"c","dear_prudence"]]],[b,null,[[f,"News \x26 Politics.Cover Story"]],
[[g,"c","cover-story"]]]];__qc.apply(null,g);(function(f){var e=function(){return B.top===B.self?m.location.href:z(m.referrer).href},g=e();setInterval(function(){var m=e();m!==g&&(g=m,__qc.apply(null,f),__qc("push",{qacct:b,event:"load"},!0))},2E3)})(g)}("p-fw53_-Tq3MNK1",window,document)}catch(nfe$$3){}quantserve();